
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Activity.cs" Link="Activity.cs" />
    <Compile Include="..\BreathingActivity.cs" Link="BreathingActivity.cs" />
    <Compile Include="..\ReflectionActivity.cs" Link="ReflectionActivity.cs" />
    <Compile Include="..\ListingActivity.cs" Link="ListingActivity.cs" />
  </ItemGroup>

</Project>
